### ISSUE TITLE
Allow customising the name of rules

### ISSUE THREAD

**Issue by aeons** [terraform-aws-modules/terraform-aws-eventbridge#20]
## Is your request related to a problem? Please describe.

When creating a rule, there is no way to customise the name of the rule generated in AWS. 
https://github.com/terraform-aws-modules/terraform-aws-eventbridge/blob/906db9f7dcc01fb5c269efd65f5762e54aa74f36/main.tf#L2-L8

We usually suffix resources with an environment. With this currently, different environments will overwrite each other's rules.

## Describe the solution you'd like.

Allow customising the name for rules.

```hcl
  rules = {
    mediaconvert_events = {
      name = "my-rule-${var.environment}"
      description = "Something"
      event_pattern = jsonencode({
        source      = ["service"],
        detail = {
          status = ["COMPLETE", "ERROR"]
        }
      })
      enabled = true
    }
  }
```

**Comment by svenlito** [comment]
I think we can introduce a `rule_suffix` parameter.

**Comment by DanteNahuelMingolo** [comment]
I don't think this was implemented yet, so I encountered the same issue. What I did to fix this is to add the prefix to the key name of the maps in rules/targets. And it works.
Example:
```
rules = {
    "${local.my_prefix}-orders" = {
      description   = "Capture all order data"
      event_pattern = jsonencode({ "source" : ["myapp.orders"] })
      enabled       = true
    }
  }

  targets = {
    "${local.my_prefix}-orders" = [
      {
        name            = "send-orders-to-sqs"
        arn             = aws_sqs_queue.queue.arn
        dead_letter_arn = aws_sqs_queue.dlq.arn
      },
      {
        name              = "send-orders-to-kinesis"
        arn               = aws_kinesis_stream.this.arn
        dead_letter_arn   = aws_sqs_queue.dlq.arn
        input_transformer = local.kinesis_input_transformer
      },
      {
        name = "log-orders-to-cloudwatch"
        arn  = aws_cloudwatch_log_group.this.arn
      }
    ]
  }
```

**Comment by TomGudman** [comment]
Ah, I had the exact same problem early this week and I came here to give the exact same answer. But @EternoSurmenage was faster :)

To add to her/his answer, you may also want to reference your allowed_triggers for a lambda like so :
```
    allowed_triggers = {
      AllowEventBridge = {
        principal  = "events.amazonaws.com"
        source_arn = module.eventbridge.eventbridge_rule_arns["${var.lambda_name}-crons"]                                                                                                                   
      }
    }
```

I hope @EternoSurmenage and my answer helps others because I bang my head on this for a little while. Where does this `cron-rules` come from?! Anyhow, it would be nice to have something simpler to use but I can understand that sometimes terraform has limited options.

PS: I cannot remember exactly but using name_prefix conflicts with name, thus I am not sure how we are meant to use it.

Good luck.
